version: '2'

services:

  frontend:
    build: ./frontend
    ports:
    - 3000:3000

  mongodb: 
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017

  backend: 
    build: ./backend
    environment:
      - MONGODB_USER=admin 
      - MONGODB_PASSWORD=admin 
      - MONGODB_HOST=mongodb
    depends_on:
      - mongodb
    ports:
      - 8080:8080