apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: my-app
    tier: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: my-app
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      tier: frontend
  template:
    metadata:
      labels:
        app: my-app
        tier: frontend
    spec:
      containers:
      - name: my-fe-container
        image: petrovskiemil/my-fe-app-hardcoded-clusterip
        ports:
        - containerPort: 3000
      restartPolicy: Always